---
- name: Deploy Diematic
  hosts: gerry1
  remote_user: gsternag
  become: yes
  become_method: sudo

  tasks:
  - name: test connection
    ping:

  - name: stop starten
    service: name=nginx state=stopped

  - name: stop gunicorn.socket
    service: name=gunicorn.socket state=stopped

  - name: copy python files
    synchronize:
        src: /Users/gsternag/Source/python/diematic/version2
        dest: /home/gsternag/src/python/diematic
        owner: yes
        group: yes
        rsync_opts:
            - "--exclude=.git"
            - "--exclude=*.pyc"
            - "--exclude=examples"
            - "--exclude=test"
            - "--exclude=tools"
            - "--exclude=web-ui-deprecated"
            - "--exclude=influxDB/venv"
            - "--exclude=diematicd/flask"
            - "--exclude=web-ui-new/flask"
 
  - name: start gunicorn.socket
    service: name=gunicorn.socket state=started

  - name: nginx starten
    service: name=nginx state=started


